// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8qP-L1Q3KdoOEC-bgedgV_qRzgc2tBuI',
    appId: '1:464843690153:web:1e08beca25adb850c099b8',
    messagingSenderId: '464843690153',
    projectId: 'eos-chatting-e371e',
    authDomain: 'eos-chatting-e371e.firebaseapp.com',
    storageBucket: 'eos-chatting-e371e.appspot.com',
    measurementId: 'G-76ECHB5PYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC55FBRuoq2cQgCnnv1rgA1NdR1S809d10',
    appId: '1:464843690153:android:d17386f84864f087c099b8',
    messagingSenderId: '464843690153',
    projectId: 'eos-chatting-e371e',
    storageBucket: 'eos-chatting-e371e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN2gaz92m464VZ7qO6UMWK7G_oZ409YI0',
    appId: '1:464843690153:ios:4f9ee36bf8230a56c099b8',
    messagingSenderId: '464843690153',
    projectId: 'eos-chatting-e371e',
    storageBucket: 'eos-chatting-e371e.appspot.com',
    iosClientId: '464843690153-rjn2pbdetdb0qsmq9jmaadqgupl0kq9t.apps.googleusercontent.com',
    iosBundleId: 'com.eos.eosChatting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN2gaz92m464VZ7qO6UMWK7G_oZ409YI0',
    appId: '1:464843690153:ios:4f9ee36bf8230a56c099b8',
    messagingSenderId: '464843690153',
    projectId: 'eos-chatting-e371e',
    storageBucket: 'eos-chatting-e371e.appspot.com',
    iosClientId: '464843690153-rjn2pbdetdb0qsmq9jmaadqgupl0kq9t.apps.googleusercontent.com',
    iosBundleId: 'com.eos.eosChatting',
  );
}
